/**
 * game/hotels.js
 * The four hotels: look (palette), guests, staff, rooms and attractions.
 * `pm` scales every price, cost and star threshold of that hotel.
 */

export const HOTELS = [
  {
    id: 'nachtruh',
    name: 'Spukhotel Nachtruh',
    short: 'Nachtruh',
    tagline: 'Gemütliche Grüfte für heimatlose Gespenster',
    icon: 'ghost',
    pm: 1,
    unlock: null,
    currencyWord: 'Übernachtung',
    bed: 'coffin',
    bar: { name: 'Nebeltee-Bar', drink: 'Nebeltee', icon: 'glass-cocktail' },
    rooms: ['Gruft 1', 'Gruft 2', 'Mondschein-Suite', 'Spinnweben-Zimmer', 'Turmkammer', 'Königsgruft'],
    guests: [
      { id: 'gespenst',    name: 'Kleines Gespenst', star: 0, mult: 1,   model: 'ghost', color: '#eef6ff', glow: '#9fd4ff' },
      { id: 'poltergeist', name: 'Poltergeist',      star: 1, mult: 1.6, model: 'ghost', color: '#d8ffe4', glow: '#6dff9e' },
      { id: 'banshee',     name: 'Banshee',          star: 2, mult: 2.5, model: 'ghost', color: '#dfe6ff', glow: '#7f9cff' },
      { id: 'graf',        name: 'Geister-Graf',     star: 3, mult: 4,   model: 'ghost', color: '#f1e3ff', glow: '#c77dff' },
      { id: 'ritter',      name: 'Kopfloser Ritter', star: 4, mult: 7,   model: 'ghost', color: '#e6eef2', glow: '#8fe3ff' },
      { id: 'koenigin',    name: 'Geisterkönigin',   star: 5, mult: 12,  model: 'ghost', color: '#fff6dc', glow: '#ffd36b' },
    ],
    staff: {
      reception: { name: 'Skelett Knochenbert', job: 'Checkt Gäste automatisch ein', model: 'skeleton', icon: 'skull' },
      cleaner:   { name: 'Zombie Modrine',      job: 'Putzt Ektoplasma automatisch',  model: 'zombie',   icon: 'broom' },
      bar:       { name: 'Hexe Kessel-Kathi',   job: 'Serviert an der Bar',            model: 'witch',    icon: 'pot-mix' },
    },
    attractions: [
      { id: 'kuerbis', name: 'Kürbisbeet',        effect: 'tips',  icon: 'sprout' },
      { id: 'orgel',   name: 'Spuk-Orgel',        effect: 'rooms', icon: 'music' },
      { id: 'brunnen', name: 'Irrlicht-Brunnen',  effect: 'spawn', icon: 'fountain' },
    ],
    palette: {
      bg: '#171230', skyTop: '#0b0a24', skyBottom: '#3a2a6a', fog: '#1d1640',
      floorA: '#7a4a33', floorB: '#6b4030', floorTex: 'planks',
      wall: '#8a7f9c', wallTex: 'bricks', trim: '#d0662f', wood: '#8b4a2b', woodDark: '#5c2f1d',
      rug: '#5a2a55', rugHi: '#8c3a9c', lounge: '#3e2a4d',
      window: '#c58bff', windowGlow: '#a45bff', slime: '#35e05a',
      ground: '#2b4632', groundTex: 'grass', path: '#6f6878',
      moon: '#fff0b0', hemiSky: '#9d8cff', hemiGround: '#3a2436', ambient: '#5b4a8a',
      key: '#ffe2c4', warm: '#ffae5b', accentLight: '#58ff7a',
      particles: 'wisps',
    },
  },
  {
    id: 'dracula',
    name: 'Burg Dracula',
    short: 'Dracula',
    tagline: 'Vornehme Särge unter dem Blutmond',
    icon: 'castle',
    pm: 12,
    unlock: { coins: 40000, hotel: 'nachtruh', stars: 3 },
    bed: 'vampireCoffin',
    bar: { name: 'Blutwein-Keller', drink: 'Blutwein', icon: 'glass-wine' },
    rooms: ['Kerkerzelle', 'Turmgemach', 'Rote Kammer', 'Fledermaus-Loft', 'Ahnengalerie', 'Draculas Suite'],
    guests: [
      { id: 'fledermaus', name: 'Fledermaus-Tourist', star: 0, mult: 1,   model: 'bat' },
      { id: 'lehrling',   name: 'Vampir-Lehrling',    star: 1, mult: 1.6, model: 'vampire', color: '#2a2a3a', cape: '#b3122e' },
      { id: 'werwolf',    name: 'Werwolf',            star: 2, mult: 2.5, model: 'werewolf' },
      { id: 'graefin',    name: 'Vampirgräfin',       star: 3, mult: 4,   model: 'countess' },
      { id: 'nosferatu',  name: 'Nosferatu',          star: 4, mult: 7,   model: 'nosferatu' },
      { id: 'dracula',    name: 'Graf Dracula',       star: 5, mult: 12,  model: 'vampire', color: '#141018', cape: '#d11a3a', crown: true },
    ],
    staff: {
      reception: { name: 'Diener Igor',          job: 'Checkt Gäste automatisch ein',   model: 'igor',   icon: 'account-tie' },
      cleaner:   { name: 'Ghul Schrubbel',       job: 'Wischt Blutflecken automatisch', model: 'ghoul',  icon: 'broom' },
      bar:       { name: 'Sommelier Vlad',       job: 'Schenkt Blutwein aus',           model: 'waiter', icon: 'glass-wine' },
    },
    attractions: [
      { id: 'rosen',  name: 'Schwarzer Rosengarten', effect: 'tips',  icon: 'flower' },
      { id: 'altar',  name: 'Blutmond-Altar',        effect: 'rooms', icon: 'moon-full' },
      { id: 'turm',   name: 'Fledermausturm',        effect: 'spawn', icon: 'castle' },
    ],
    palette: {
      bg: '#1a0a14', skyTop: '#12040c', skyBottom: '#5a1426', fog: '#240a16',
      floorA: '#4a4250', floorB: '#3f3845', floorTex: 'tiles',
      wall: '#5d5566', wallTex: 'bricks', trim: '#5a1a26', wood: '#4a2420', woodDark: '#2e1512',
      rug: '#4a0c18', rugHi: '#6e1426', lounge: '#2e0a14',
      window: '#ff8a6b', windowGlow: '#d8202e', slime: '#a0102a',
      ground: '#23262a', groundTex: 'grass', path: '#55505c',
      moon: '#ff8a70', hemiSky: '#ff8aa0', hemiGround: '#2a0c16', ambient: '#6a2a44',
      key: '#ffd8c8', warm: '#ff9a5a', accentLight: '#ff3a4a',
      particles: 'bats',
    },
  },
  {
    id: 'pyramide',
    name: 'Pharaonengrab',
    short: 'Pyramide',
    tagline: 'Ewige Ruhe mit Blick auf den Nil',
    icon: 'pyramid',
    pm: 150,
    unlock: { coins: 600000, hotel: 'dracula', stars: 3 },
    bed: 'sarcophagus',
    bar: { name: 'Nilnektar-Oase', drink: 'Nilnektar', icon: 'cup' },
    rooms: ['Grabkammer', 'Sonnenkammer', 'Skarabäus-Suite', 'Papyrus-Zimmer', 'Goldene Halle', 'Pharaonengemach'],
    guests: [
      { id: 'skarabaeus', name: 'Skarabäus',          star: 0, mult: 1,   model: 'beetle' },
      { id: 'mumie',      name: 'Mumie',              star: 1, mult: 1.6, model: 'mummy' },
      { id: 'bastet',     name: 'Bastet-Katze',       star: 2, mult: 2.5, model: 'cat' },
      { id: 'anubis',     name: 'Anubis-Wächter',     star: 3, mult: 4,   model: 'anubis' },
      { id: 'priesterin', name: 'Hohepriesterin',     star: 4, mult: 7,   model: 'priestess' },
      { id: 'pharao',     name: 'Pharao',             star: 5, mult: 12,  model: 'pharaoh' },
    ],
    staff: {
      reception: { name: 'Mumien-Portier Ramses', job: 'Checkt Gäste automatisch ein', model: 'mummy',   icon: 'account-tie' },
      cleaner:   { name: 'Skarabäus-Kolonne',     job: 'Rollt Sand automatisch weg',   model: 'beetleCart', icon: 'broom' },
      bar:       { name: 'Priesterin Neferu',     job: 'Serviert Nilnektar',           model: 'priestess', icon: 'cup' },
    },
    attractions: [
      { id: 'skarabrunnen', name: 'Goldener Skarabäus', effect: 'tips',  icon: 'bug' },
      { id: 'obelisk',      name: 'Obelisk der Ewigkeit', effect: 'rooms', icon: 'pillar' },
      { id: 'sphinx',       name: 'Sphinx',             effect: 'spawn', icon: 'cat' },
    ],
    palette: {
      bg: '#0f1430', skyTop: '#070b20', skyBottom: '#2a3a78', fog: '#141b3e',
      floorA: '#c29a62', floorB: '#b58d58', floorTex: 'tiles',
      wall: '#d2ad74', wallTex: 'sandstone', trim: '#e5b53f', wood: '#8a5a2a', woodDark: '#5a3a1a',
      rug: '#1f7d82', rugHi: '#2aa6a6', lounge: '#1b5f66',
      window: '#ffcf6b', windowGlow: '#ff9a2a', slime: '#e0b050',
      ground: '#c7a468', groundTex: 'sand', path: '#b09060',
      moon: '#fff6dc', hemiSky: '#8ab0ff', hemiGround: '#5a3a1a', ambient: '#4a5a8a',
      key: '#ffe8c0', warm: '#ffb14a', accentLight: '#3fe0e0',
      particles: 'sand',
    },
  },
  {
    id: 'eispalast',
    name: 'Yeti-Eispalast',
    short: 'Eispalast',
    tagline: 'Frostige Luxus-Iglus unter dem Nordlicht',
    icon: 'snowflake',
    pm: 2000,
    unlock: { coins: 9000000, hotel: 'pyramide', stars: 3 },
    bed: 'iceBed',
    bar: { name: 'Frostpunsch-Bar', drink: 'Frostpunsch', icon: 'glass-mug-variant' },
    rooms: ['Iglu-Zimmer', 'Schneehöhle', 'Kristallkammer', 'Polarlicht-Suite', 'Gletscher-Loft', 'Yeti-Palastsuite'],
    guests: [
      { id: 'schneegeist', name: 'Schneegeist',  star: 0, mult: 1,   model: 'snowSprite' },
      { id: 'wichtel',     name: 'Eiswichtel',   star: 1, mult: 1.6, model: 'gnome' },
      { id: 'pinguin',     name: 'Geisterpinguin', star: 2, mult: 2.5, model: 'penguin' },
      { id: 'yeti',        name: 'Yeti',         star: 3, mult: 4,   model: 'yeti' },
      { id: 'frostelfe',   name: 'Frostelfe',    star: 4, mult: 7,   model: 'elf' },
      { id: 'eiskoenigin', name: 'Eiskönigin',   star: 5, mult: 12,  model: 'iceQueen' },
    ],
    staff: {
      reception: { name: 'Pinguin-Butler Frack',  job: 'Checkt Gäste automatisch ein', model: 'penguinButler', icon: 'account-tie' },
      cleaner:   { name: 'Schneemann Flocke',     job: 'Fegt Schneematsch automatisch', model: 'snowman',      icon: 'broom' },
      bar:       { name: 'Yeti-Barkeeper Brumm',  job: 'Mixt Frostpunsch',              model: 'yeti',         icon: 'glass-mug-variant' },
    },
    attractions: [
      { id: 'skulptur', name: 'Eisskulpturen',  effect: 'tips',  icon: 'diamond' },
      { id: 'harfe',    name: 'Nordlicht-Harfe', effect: 'rooms', icon: 'music-clef-treble' },
      { id: 'quelle',   name: 'Heiße Quelle',    effect: 'spawn', icon: 'hot-tub' },
    ],
    palette: {
      bg: '#0a1a30', skyTop: '#050d20', skyBottom: '#15406a', fog: '#10284a',
      floorA: '#8fb8d4', floorB: '#7faac8', floorTex: 'ice',
      wall: '#6fa4cc', wallTex: 'iceBricks', trim: '#cfe4f4', wood: '#7a5a4a', woodDark: '#4a3a30',
      rug: '#8a5a3a', rugHi: '#b07a4a', lounge: '#2a5a8a',
      window: '#9ff6ff', windowGlow: '#3fd8ff', slime: '#8fe8ff',
      ground: '#a9c2d8', groundTex: 'snow', path: '#8aa6c0',
      moon: '#eaffff', hemiSky: '#9fdcff', hemiGround: '#3a5a7a', ambient: '#4a7aa8',
      key: '#cfe8ff', warm: '#ffb86b', accentLight: '#4ff0ff',
      particles: 'snow',
    },
  },
];

export const getHotel = (id) => HOTELS.find(h => h.id === id) ?? HOTELS[0];

export const getGuestDef = (hotel, id) => hotel.guests.find(g => g.id === id) ?? hotel.guests[0];
