/**
 * game/hotels.js
 * The four hotels: look (palette), guests, staff, rooms and attractions.
 * `pm` scales every price, cost and star threshold of that hotel.
 */

export const HOTELS = [
  {
    id: 'nachtruh',
    name: 'Spukhotel Nachtruh',
    short: 'Nachtruh',
    tagline: 'Gemütliche Grüfte für heimatlose Gespenster',
    icon: 'ghost',
    pm: 1,
    unlock: null,
    currencyWord: 'Übernachtung',
    bed: 'coffin',
    bar: { name: 'Nebeltee-Bar', drink: 'Nebeltee', icon: 'glass-cocktail' },
    rooms: ['Gruft 1', 'Gruft 2', 'Mondschein-Suite', 'Spinnweben-Zimmer', 'Turmkammer', 'Königsgruft'],
    guests: [
      { id: 'gespenst',    name: 'Kleines Gespenst', star: 0, mult: 1,   model: 'ghost', color: '#eef6ff', glow: '#9fd4ff' },
      { id: 'poltergeist', name: 'Poltergeist',      star: 1, mult: 1.6, model: 'ghost', color: '#d8ffe4', glow: '#6dff9e' },
      { id: 'banshee',     name: 'Banshee',          star: 2, mult: 2.5, model: 'ghost', color: '#dfe6ff', glow: '#7f9cff' },
      { id: 'graf',        name: 'Geister-Graf',     star: 3, mult: 4,   model: 'ghost', color: '#f1e3ff', glow: '#c77dff' },
      { id: 'ritter',      name: 'Kopfloser Ritter', star: 4, mult: 7,   model: 'ghost', color: '#e6eef2', glow: '#8fe3ff' },
      { id: 'koenigin',    name: 'Geisterkönigin',   star: 5, mult: 12,  model: 'ghost', color: '#fff6dc', glow: '#ffd36b' },
    ],
    staff: {
      reception: { name: 'Skelett Knochenbert', job: 'Checkt Gäste automatisch ein', model: 'skeleton', icon: 'skull' },
      cleaner:   { name: 'Zombie Modrine',      job: 'Putzt Ektoplasma automatisch',  model: 'zombie',   icon: 'broom' },
      bar:       { name: 'Hexe Kessel-Kathi',   job: 'Serviert an der Bar',            model: 'witch',    icon: 'pot-mix' },
    },
    attractions: [
      { id: 'kuerbis', name: 'Kürbisbeet',        effect: 'tips',  icon: 'sprout' },
      { id: 'orgel',   name: 'Spuk-Orgel',        effect: 'rooms', icon: 'music' },
      { id: 'brunnen', name: 'Irrlicht-Brunnen',  effect: 'spawn', icon: 'fountain' },
    ],
    palette: {
      bg: '#7b6fd6', skyTop: '#5a4fc0', skyBottom: '#c89ae8', fog: '#9a8fe0',
      floorA: '#e8b77a', floorB: '#d9a468', floorTex: 'cleanPlanks',
      wall: '#9d93dc', wallTex: null, trim: '#ff8a3d', wood: '#c07a48', woodDark: '#8a5232',
      rug: '#b04ac8', rugHi: '#d67ae8', lounge: '#7a56c8',
      window: '#fff4a8', windowGlow: '#ffd24a', slime: '#5ce65c',
      ground: '#6cc460', groundTex: 'cleanGrass', path: '#d6d0e4',
      moon: '#fff6d0', hemiSky: '#ffffff', hemiGround: '#8a7ab0', ambient: '#ffffff',
      key: '#fff4e6', warm: '#ffb45a', accentLight: '#6aff8a',
      particles: 'wisps',
    },
  },
  {
    id: 'dracula',
    name: 'Burg Dracula',
    short: 'Dracula',
    tagline: 'Vornehme Särge unter dem Blutmond',
    icon: 'castle',
    pm: 12,
    unlock: { coins: 40000, hotel: 'nachtruh', stars: 3 },
    bed: 'vampireCoffin',
    bar: { name: 'Blutwein-Keller', drink: 'Blutwein', icon: 'glass-wine' },
    rooms: ['Kerkerzelle', 'Turmgemach', 'Rote Kammer', 'Fledermaus-Loft', 'Ahnengalerie', 'Draculas Suite'],
    guests: [
      { id: 'fledermaus', name: 'Fledermaus-Tourist', star: 0, mult: 1,   model: 'bat' },
      { id: 'lehrling',   name: 'Vampir-Lehrling',    star: 1, mult: 1.6, model: 'vampire', color: '#2a2a3a', cape: '#b3122e' },
      { id: 'werwolf',    name: 'Werwolf',            star: 2, mult: 2.5, model: 'werewolf' },
      { id: 'graefin',    name: 'Vampirgräfin',       star: 3, mult: 4,   model: 'countess' },
      { id: 'nosferatu',  name: 'Nosferatu',          star: 4, mult: 7,   model: 'nosferatu' },
      { id: 'dracula',    name: 'Graf Dracula',       star: 5, mult: 12,  model: 'vampire', color: '#141018', cape: '#d11a3a', crown: true },
    ],
    staff: {
      reception: { name: 'Diener Igor',          job: 'Checkt Gäste automatisch ein',   model: 'igor',   icon: 'account-tie' },
      cleaner:   { name: 'Ghul Schrubbel',       job: 'Wischt Blutflecken automatisch', model: 'ghoul',  icon: 'broom' },
      bar:       { name: 'Sommelier Vlad',       job: 'Schenkt Blutwein aus',           model: 'waiter', icon: 'glass-wine' },
    },
    attractions: [
      { id: 'rosen',  name: 'Schwarzer Rosengarten', effect: 'tips',  icon: 'flower' },
      { id: 'altar',  name: 'Blutmond-Altar',        effect: 'rooms', icon: 'moon-full' },
      { id: 'turm',   name: 'Fledermausturm',        effect: 'spawn', icon: 'castle' },
    ],
    palette: {
      bg: '#d86a8a', skyTop: '#b04a7a', skyBottom: '#ffb0a0', fog: '#e08aa0',
      floorA: '#d9ccc4', floorB: '#c8b8ae', floorTex: 'cleanTiles',
      wall: '#a89fb8', wallTex: null, trim: '#e0344c', wood: '#8a4a3a', woodDark: '#5e2e28',
      rug: '#d6334a', rugHi: '#f05a6e', lounge: '#b02a44',
      window: '#fff0c0', windowGlow: '#ffb04a', slime: '#e0344c',
      ground: '#7cb05a', groundTex: 'cleanGrass', path: '#c8c0cc',
      moon: '#ffe0d0', hemiSky: '#ffffff', hemiGround: '#a07a8a', ambient: '#ffffff',
      key: '#fff0e6', warm: '#ffb45a', accentLight: '#ff5a6a',
      particles: 'bats',
    },
  },
  {
    id: 'pyramide',
    name: 'Pharaonengrab',
    short: 'Pyramide',
    tagline: 'Ewige Ruhe mit Blick auf den Nil',
    icon: 'pyramid',
    pm: 150,
    unlock: { coins: 600000, hotel: 'dracula', stars: 3 },
    bed: 'sarcophagus',
    bar: { name: 'Nilnektar-Oase', drink: 'Nilnektar', icon: 'cup' },
    rooms: ['Grabkammer', 'Sonnenkammer', 'Skarabäus-Suite', 'Papyrus-Zimmer', 'Goldene Halle', 'Pharaonengemach'],
    guests: [
      { id: 'skarabaeus', name: 'Skarabäus',          star: 0, mult: 1,   model: 'beetle' },
      { id: 'mumie',      name: 'Mumie',              star: 1, mult: 1.6, model: 'mummy' },
      { id: 'bastet',     name: 'Bastet-Katze',       star: 2, mult: 2.5, model: 'cat' },
      { id: 'anubis',     name: 'Anubis-Wächter',     star: 3, mult: 4,   model: 'anubis' },
      { id: 'priesterin', name: 'Hohepriesterin',     star: 4, mult: 7,   model: 'priestess' },
      { id: 'pharao',     name: 'Pharao',             star: 5, mult: 12,  model: 'pharaoh' },
    ],
    staff: {
      reception: { name: 'Mumien-Portier Ramses', job: 'Checkt Gäste automatisch ein', model: 'mummy',   icon: 'account-tie' },
      cleaner:   { name: 'Skarabäus-Kolonne',     job: 'Rollt Sand automatisch weg',   model: 'beetleCart', icon: 'broom' },
      bar:       { name: 'Priesterin Neferu',     job: 'Serviert Nilnektar',           model: 'priestess', icon: 'cup' },
    },
    attractions: [
      { id: 'skarabrunnen', name: 'Goldener Skarabäus', effect: 'tips',  icon: 'bug' },
      { id: 'obelisk',      name: 'Obelisk der Ewigkeit', effect: 'rooms', icon: 'pillar' },
      { id: 'sphinx',       name: 'Sphinx',             effect: 'spawn', icon: 'cat' },
    ],
    palette: {
      bg: '#62c6ff', skyTop: '#3aa8ff', skyBottom: '#bfeaff', fog: '#9adcff',
      floorA: '#f8dfac', floorB: '#f0d098', floorTex: 'cleanTiles',
      wall: '#f2c784', wallTex: null, trim: '#22b0b0', wood: '#c08040', woodDark: '#8a5a2a',
      rug: '#22b0b0', rugHi: '#4ad6d0', lounge: '#1f9a9a',
      window: '#fff6c0', windowGlow: '#ffd24a', slime: '#f0b040',
      ground: '#f6d38e', groundTex: 'cleanSand', path: '#e8c890',
      moon: '#ffffff', hemiSky: '#ffffff', hemiGround: '#c8a060', ambient: '#ffffff',
      key: '#fff6e0', warm: '#ffb45a', accentLight: '#3fe0e0',
      particles: 'sand',
    },
  },
  {
    id: 'eispalast',
    name: 'Yeti-Eispalast',
    short: 'Eispalast',
    tagline: 'Frostige Luxus-Iglus unter dem Nordlicht',
    icon: 'snowflake',
    pm: 2000,
    unlock: { coins: 9000000, hotel: 'pyramide', stars: 3 },
    bed: 'iceBed',
    bar: { name: 'Frostpunsch-Bar', drink: 'Frostpunsch', icon: 'glass-mug-variant' },
    rooms: ['Iglu-Zimmer', 'Schneehöhle', 'Kristallkammer', 'Polarlicht-Suite', 'Gletscher-Loft', 'Yeti-Palastsuite'],
    guests: [
      { id: 'schneegeist', name: 'Schneegeist',  star: 0, mult: 1,   model: 'snowSprite' },
      { id: 'wichtel',     name: 'Eiswichtel',   star: 1, mult: 1.6, model: 'gnome' },
      { id: 'pinguin',     name: 'Geisterpinguin', star: 2, mult: 2.5, model: 'penguin' },
      { id: 'yeti',        name: 'Yeti',         star: 3, mult: 4,   model: 'yeti' },
      { id: 'frostelfe',   name: 'Frostelfe',    star: 4, mult: 7,   model: 'elf' },
      { id: 'eiskoenigin', name: 'Eiskönigin',   star: 5, mult: 12,  model: 'iceQueen' },
    ],
    staff: {
      reception: { name: 'Pinguin-Butler Frack',  job: 'Checkt Gäste automatisch ein', model: 'penguinButler', icon: 'account-tie' },
      cleaner:   { name: 'Schneemann Flocke',     job: 'Fegt Schneematsch automatisch', model: 'snowman',      icon: 'broom' },
      bar:       { name: 'Yeti-Barkeeper Brumm',  job: 'Mixt Frostpunsch',              model: 'yeti',         icon: 'glass-mug-variant' },
    },
    attractions: [
      { id: 'skulptur', name: 'Eisskulpturen',  effect: 'tips',  icon: 'diamond' },
      { id: 'harfe',    name: 'Nordlicht-Harfe', effect: 'rooms', icon: 'music-clef-treble' },
      { id: 'quelle',   name: 'Heiße Quelle',    effect: 'spawn', icon: 'hot-tub' },
    ],
    palette: {
      bg: '#6ac2ff', skyTop: '#3a9cff', skyBottom: '#d8f2ff', fog: '#b0e0ff',
      floorA: '#e2f4ff', floorB: '#cdeaff', floorTex: 'cleanTiles',
      wall: '#8ccdf6', wallTex: null, trim: '#ffffff', wood: '#b07a5a', woodDark: '#7a5040',
      rug: '#ff8a5a', rugHi: '#ffb07a', lounge: '#4a9ae0',
      window: '#e0fbff', windowGlow: '#6ae8ff', slime: '#6ad8ff',
      ground: '#f4faff', groundTex: 'cleanSnow', path: '#c8def0',
      moon: '#ffffff', hemiSky: '#ffffff', hemiGround: '#a0c0e0', ambient: '#ffffff',
      key: '#ffffff', warm: '#ffb45a', accentLight: '#4ff0ff',
      particles: 'snow',
    },
  },
];

export const getHotel = (id) => HOTELS.find(h => h.id === id) ?? HOTELS[0];

export const getGuestDef = (hotel, id) => hotel.guests.find(g => g.id === id) ?? hotel.guests[0];
