/**
 * game/hotels.js
 * The four hotels: look (palette), guests, staff, rooms and attractions.
 * `pm` scales every price, cost and star threshold of that hotel.
 */

export const HOTELS = [
  {
    id: 'nachtruh',
    name: 'Spukhotel Nachtruh',
    short: 'Nachtruh',
    tagline: 'Gemütliche Grüfte für heimatlose Gespenster',
    icon: 'ghost',
    pm: 1,
    unlock: null,
    currencyWord: 'Übernachtung',
    bed: 'coffin',
    bar: { name: 'Nebeltee-Bar', drink: 'Nebeltee', icon: 'glass-cocktail' },
    rooms: ['Gruft 1', 'Gruft 2', 'Mondschein-Suite', 'Spinnweben-Zimmer', 'Turmkammer', 'Königsgruft'],
    guests: [
      { id: 'gespenst',    name: 'Kleines Gespenst', star: 0, mult: 1,   model: 'ghost', color: '#eef6ff', glow: '#9fd4ff' },
      { id: 'poltergeist', name: 'Poltergeist',      star: 1, mult: 1.6, model: 'ghost', color: '#d8ffe4', glow: '#6dff9e' },
      { id: 'banshee',     name: 'Banshee',          star: 2, mult: 2.5, model: 'ghost', color: '#dfe6ff', glow: '#7f9cff' },
      { id: 'graf',        name: 'Geister-Graf',     star: 3, mult: 4,   model: 'ghost', color: '#f1e3ff', glow: '#c77dff' },
      { id: 'ritter',      name: 'Kopfloser Ritter', star: 4, mult: 7,   model: 'ghost', color: '#e6eef2', glow: '#8fe3ff' },
      { id: 'koenigin',    name: 'Geisterkönigin',   star: 5, mult: 12,  model: 'ghost', color: '#fff6dc', glow: '#ffd36b' },
    ],
    staff: {
      reception: { name: 'Skelett Knochenbert', job: 'Checkt Gäste automatisch ein', model: 'skeleton', icon: 'skull' },
      cleaner:   { name: 'Zombie Modrine',      job: 'Putzt Ektoplasma automatisch',  model: 'zombie',   icon: 'broom' },
      bar:       { name: 'Hexe Kessel-Kathi',   job: 'Serviert an der Bar',            model: 'witch',    icon: 'pot-mix' },
    },
    attractions: [
      { id: 'kuerbis', name: 'Kürbisbeet',        effect: 'tips',  icon: 'sprout' },
      { id: 'orgel',   name: 'Spuk-Orgel',        effect: 'rooms', icon: 'music' },
      { id: 'brunnen', name: 'Irrlicht-Brunnen',  effect: 'spawn', icon: 'fountain' },
    ],
    palette: {
      // Halloween night: plum walls, pumpkin orange, moss green, glowing windows
      bg: '#1c1433', skyTop: '#120c26', skyBottom: '#4a2a66', fog: '#241a40',
      floorA: '#6e4e3c', floorB: '#654636', floorTex: 'cleanPlanks',
      wall: '#584c70', wallTex: null, trim: '#ff7a1a', wood: '#7a4a2e', woodDark: '#4a2a1c',
      rug: '#5a3a7a', rugHi: '#ff7a1a', lounge: '#6a3a8a',
      window: '#ffc24a', windowGlow: '#ff9a1a', slime: '#7dff5a',
      ground: '#3a5842', groundTex: 'cleanGrass', path: '#6e6680',
      moon: '#fff2c0', hemiSky: '#9a8ae8', hemiGround: '#231a36', ambient: '#ffffff',
      key: '#d6ccff', warm: '#ff9a3a', accentLight: '#7dff8a',
      light: { hemi: 1.0, ambient: 0.45, key: 1.9 },
      wallTop: '#8c7ca8',
      zoneRoom: '#553a78',
      zoneBar: '#2e6656',
      zoneLounge: '#a8521e',
      zoneDesk: '#3a3a70',
      road: '#2a2634',
      hedge: '#27452f', flowers: ['#ff7a1a', '#a86af0', '#d8ff7a', '#ffd23a'],
      cars: ['#1a1622', '#5a2a7a', '#b8561e'],
      particles: 'wisps',
    },
  },
  {
    id: 'dracula',
    name: 'Burg Dracula',
    short: 'Dracula',
    tagline: 'Vornehme Särge unter dem Blutmond',
    icon: 'castle',
    pm: 12,
    unlock: { coins: 40000, hotel: 'nachtruh', stars: 3 },
    bed: 'vampireCoffin',
    bar: { name: 'Blutwein-Keller', drink: 'Blutwein', icon: 'glass-wine' },
    rooms: ['Kerkerzelle', 'Turmgemach', 'Rote Kammer', 'Fledermaus-Loft', 'Ahnengalerie', 'Draculas Suite',
      'Blutmond-Kammer', 'Nachtflügel-Suite'],
    guests: [
      { id: 'fledermaus', name: 'Fledermaus-Tourist', star: 0, mult: 1,   model: 'bat' },
      { id: 'lehrling',   name: 'Vampir-Lehrling',    star: 1, mult: 1.6, model: 'vampire', color: '#6a4ab0', cape: '#e0344c' },
      { id: 'werwolf',    name: 'Werwolf',            star: 2, mult: 2.5, model: 'werewolf' },
      { id: 'graefin',    name: 'Vampirgräfin',       star: 3, mult: 4,   model: 'countess' },
      { id: 'nosferatu',  name: 'Nosferatu',          star: 4, mult: 7,   model: 'nosferatu' },
      { id: 'dracula',    name: 'Graf Dracula',       star: 5, mult: 12,  model: 'vampire', color: '#4a2a6a', cape: '#e0344c', crown: true },
    ],
    staff: {
      reception: { name: 'Diener Igor',          job: 'Checkt Gäste automatisch ein',   model: 'igor',   icon: 'account-tie' },
      cleaner:   { name: 'Ghul Schrubbel',       job: 'Wischt Blutflecken automatisch', model: 'ghoul',  icon: 'broom' },
      bar:       { name: 'Sommelier Vlad',       job: 'Schenkt Blutwein aus',           model: 'waiter', icon: 'glass-wine' },
    },
    attractions: [
      { id: 'rosen',  name: 'Schwarzer Rosengarten', effect: 'tips',  icon: 'flower' },
      { id: 'altar',  name: 'Blutmond-Altar',        effect: 'rooms', icon: 'moon-full' },
      { id: 'turm',   name: 'Fledermausturm',        effect: 'spawn', icon: 'castle' },
    ],
    palette: {
      // blood moon over black stone: crimson, wine, cold stone, torch orange
      bg: '#1a0a14', skyTop: '#10050c', skyBottom: '#6a1426', fog: '#240c18',
      floorA: '#4e3436', floorB: '#462e30', floorTex: 'cleanTiles',
      wall: '#56505e', wallTex: null, trim: '#e0344c', wood: '#5e2e28', woodDark: '#381816',
      rug: '#6a1420', rugHi: '#d0243e', lounge: '#6a1420',
      window: '#ffb04a', windowGlow: '#ff6a2a', slime: '#e0344c',
      ground: '#34403a', groundTex: 'cleanGrass', path: '#645c68',
      moon: '#ff8a7a', hemiSky: '#c08aa0', hemiGround: '#1e1016', ambient: '#ffffff',
      key: '#ffc8c8', warm: '#ff8a3a', accentLight: '#ff4a5a',
      light: { hemi: 1.0, ambient: 0.42, key: 1.85 },
      wallTop: '#857a8e',
      zoneRoom: '#6e1624',
      zoneBar: '#432056',
      zoneLounge: '#8a3218',
      zoneDesk: '#2a2a4e',
      road: '#221c24',
      hedge: '#22362a', flowers: ['#c21a3a', '#ff4a5a', '#2a1a2a', '#ffb04a'],
      cars: ['#120c10', '#6a0a1a', '#3a343e'],
      particles: 'bats',
    },
  },
  {
    id: 'pyramide',
    name: 'Pharaonengrab',
    short: 'Pyramide',
    tagline: 'Ewige Ruhe mit Blick auf den Nil',
    icon: 'pyramid',
    pm: 150,
    unlock: { coins: 600000, hotel: 'dracula', stars: 3 },
    bed: 'sarcophagus',
    bar: { name: 'Nilnektar-Oase', drink: 'Nilnektar', icon: 'cup' },
    rooms: ['Grabkammer', 'Sonnenkammer', 'Skarabäus-Suite', 'Papyrus-Zimmer', 'Goldene Halle', 'Pharaonengemach',
      'Anubis-Zimmer', 'Nil-Suite'],
    guests: [
      { id: 'skarabaeus', name: 'Skarabäus',          star: 0, mult: 1,   model: 'beetle' },
      { id: 'mumie',      name: 'Mumie',              star: 1, mult: 1.6, model: 'mummy' },
      { id: 'bastet',     name: 'Bastet-Katze',       star: 2, mult: 2.5, model: 'cat' },
      { id: 'anubis',     name: 'Anubis-Wächter',     star: 3, mult: 4,   model: 'anubis' },
      { id: 'priesterin', name: 'Hohepriesterin',     star: 4, mult: 7,   model: 'priestess' },
      { id: 'pharao',     name: 'Pharao',             star: 5, mult: 12,  model: 'pharaoh' },
    ],
    staff: {
      reception: { name: 'Mumien-Portier Ramses', job: 'Checkt Gäste automatisch ein', model: 'mummy',   icon: 'account-tie' },
      cleaner:   { name: 'Skarabäus-Kolonne',     job: 'Rollt Sand automatisch weg',   model: 'beetleCart', icon: 'broom' },
      bar:       { name: 'Priesterin Neferu',     job: 'Serviert Nilnektar',           model: 'priestess', icon: 'cup' },
    },
    attractions: [
      { id: 'skarabrunnen', name: 'Goldener Skarabäus', effect: 'tips',  icon: 'bug' },
      { id: 'obelisk',      name: 'Obelisk der Ewigkeit', effect: 'rooms', icon: 'pillar' },
      { id: 'sphinx',       name: 'Sphinx',             effect: 'spawn', icon: 'cat' },
    ],
    palette: {
      // desert dusk in the tomb valley: dark sandstone, turquoise, torch gold
      bg: '#24152e', skyTop: '#170e2a', skyBottom: '#b8501e', fog: '#3a1e2a',
      floorA: '#9a7a50', floorB: '#90704a', floorTex: 'cleanTiles',
      wall: '#9c7c4c', wallTex: null, trim: '#22b0b0', wood: '#8a5a2a', woodDark: '#5a3a1a',
      rug: '#1f6a6e', rugHi: '#2ad0c0', lounge: '#1f6a6e',
      window: '#ffc860', windowGlow: '#ff9a2a', slime: '#f0b040',
      ground: '#94744a', groundTex: 'cleanSand', path: '#846a4a',
      moon: '#ffe8b0', hemiSky: '#e8a878', hemiGround: '#3a2418', ambient: '#ffffff',
      key: '#ffd0a0', warm: '#ffa03a', accentLight: '#3fe0e0',
      light: { hemi: 0.95, ambient: 0.42, key: 1.9 },
      wallTop: '#d4b47a',
      zoneRoom: '#1c6468',
      zoneBar: '#7a3a1c',
      zoneLounge: '#a8661a',
      zoneDesk: '#44286a',
      road: '#5e4a36',
      hedge: '#3a5a2a', flowers: ['#2ad0c0', '#ffc83a', '#ff7a3a', '#a86af0'],
      cars: ['#c09050', '#1c6468', '#7a3a1c'],
      particles: 'sand',
    },
  },
  {
    id: 'eispalast',
    name: 'Yeti-Eispalast',
    short: 'Eispalast',
    tagline: 'Frostige Luxus-Iglus unter dem Nordlicht',
    icon: 'snowflake',
    pm: 2000,
    unlock: { coins: 9000000, hotel: 'pyramide', stars: 3 },
    bed: 'iceBed',
    bar: { name: 'Frostpunsch-Bar', drink: 'Frostpunsch', icon: 'glass-mug-variant' },
    rooms: ['Iglu-Zimmer', 'Schneehöhle', 'Kristallkammer', 'Polarlicht-Suite', 'Gletscher-Loft', 'Yeti-Palastsuite',
      'Nordwind-Zimmer', 'Eiszapfen-Kammer', 'Schneeflocken-Suite', 'Kronjuwel-Suite'],
    guests: [
      { id: 'schneegeist', name: 'Schneegeist',  star: 0, mult: 1,   model: 'snowSprite' },
      { id: 'wichtel',     name: 'Eiswichtel',   star: 1, mult: 1.6, model: 'gnome' },
      { id: 'pinguin',     name: 'Geisterpinguin', star: 2, mult: 2.5, model: 'penguin' },
      { id: 'yeti',        name: 'Yeti',         star: 3, mult: 4,   model: 'yeti' },
      { id: 'frostelfe',   name: 'Frostelfe',    star: 4, mult: 7,   model: 'elf' },
      { id: 'eiskoenigin', name: 'Eiskönigin',   star: 5, mult: 12,  model: 'iceQueen' },
    ],
    staff: {
      reception: { name: 'Pinguin-Butler Frack',  job: 'Checkt Gäste automatisch ein', model: 'penguinButler', icon: 'account-tie' },
      cleaner:   { name: 'Schneemann Flocke',     job: 'Fegt Schneematsch automatisch', model: 'snowman',      icon: 'broom' },
      bar:       { name: 'Yeti-Barkeeper Brumm',  job: 'Mixt Frostpunsch',              model: 'yeti',         icon: 'glass-mug-variant' },
    },
    attractions: [
      { id: 'skulptur', name: 'Eisskulpturen',  effect: 'tips',  icon: 'diamond' },
      { id: 'harfe',    name: 'Nordlicht-Harfe', effect: 'rooms', icon: 'music-clef-treble' },
      { id: 'quelle',   name: 'Heiße Quelle',    effect: 'spawn', icon: 'hot-tub' },
    ],
    palette: {
      // polar night under the aurora: ice blue, deep indigo, cold cyan glow
      bg: '#0c1630', skyTop: '#070e24', skyBottom: '#1e5a7a', fog: '#122240',
      floorA: '#4a6488', floorB: '#445c7e', floorTex: 'cleanTiles',
      wall: '#5c7698', wallTex: null, trim: '#8af0ff', wood: '#6a4a3a', woodDark: '#43302a',
      rug: '#2a4a8a', rugHi: '#5ae0ff', lounge: '#3a2a7a',
      window: '#c8f6ff', windowGlow: '#4ae0ff', slime: '#6ad8ff',
      ground: '#a4b8d4', groundTex: 'cleanSnow', path: '#6a809e',
      moon: '#e8f4ff', hemiSky: '#9ab8ff', hemiGround: '#1a2440', ambient: '#ffffff',
      key: '#c8dcff', warm: '#ffb45a', accentLight: '#4ff0ff',
      light: { hemi: 0.95, ambient: 0.42, key: 1.8 },
      wallTop: '#c4dcf4',
      zoneRoom: '#2c4a86',
      zoneBar: '#1a6480',
      zoneLounge: '#4c3494',
      zoneDesk: '#1c3a66',
      road: '#2a3448',
      hedge: '#1f3a3a', flowers: ['#8af0ff', '#ffffff', '#a86af0', '#5ae0ff'],
      cars: ['#1a2a4a', '#8a1a2a', '#c8d4e4'],
      particles: 'snow',
    },
  },
];

export const getHotel = (id) => HOTELS.find(h => h.id === id) ?? HOTELS[0];

export const getGuestDef = (hotel, id) => hotel.guests.find(g => g.id === id) ?? hotel.guests[0];
