"""
Packs a rendered hotel (render_hotel.py + render_chars.py output) into
texture atlases for the game and writes the asset module.

Usage: python pack.py <renderDir> <glbDir> <hotel> <assetsDir>
Output: <assetsDir>/<hotel>/atlas-<n>.webp, backdrop-<c>-<r>.webp,
        pack.json (sprite table) and index.js (require() list for Metro).

Also records for every station part at which export levels it exists
("presence"), read straight from the glTF node extras.
"""
import json
import os
import struct
import sys

from PIL import Image

PAGE = 2048
PAD = 2
LEVELS = [0, 1, 2, 3, 4, 6, 7, 10]


def glb_parts(path):
    with open(path, 'rb') as f:
        data = f.read()
    length = struct.unpack_from('<I', data, 12)[0]
    doc = json.loads(data[20:20 + length])
    out = set()
    for node in doc.get('nodes', []):
        ex = node.get('extras') or {}
        if ex.get('part') and ex.get('station'):
            out.add(ex['part'])
    return out


def shelf_pack(items):
    """items: list of (key, w, h) -> {key: (page, x, y)}"""
    placed = {}
    page, x, y, row_h = 0, 0, 0, 0
    for key, w, h in sorted(items, key=lambda i: -i[2]):
        w2, h2 = w + PAD * 2, h + PAD * 2
        if x + w2 > PAGE:
            x, y, row_h = 0, y + row_h, 0
        if y + h2 > PAGE:
            page, x, y, row_h = page + 1, 0, 0, 0
        placed[key] = (page, x + PAD, y + PAD)
        x += w2
        row_h = max(row_h, h2)
    return placed, page + 1


def write_registry(assets):
    hotels = sorted(d for d in os.listdir(assets) if os.path.isfile(os.path.join(assets, d, 'index.js')))
    lines = ['// generated by tools/sprites/pack.py — hotels with pre-rendered sprites', 'export default {']
    lines += [f"  {h}: () => require('./{h}').default," for h in hotels]
    lines += ['};', '']
    with open(os.path.join(assets, 'index.js'), 'w') as f:
        f.write('\n'.join(lines))


def main():
    render_dir, glb_dir, hotel, assets = sys.argv[1:5]
    out = os.path.join(assets, hotel)
    os.makedirs(out, exist_ok=True)
    for f in os.listdir(out):
        os.remove(os.path.join(out, f))
    man = json.load(open(os.path.join(render_dir, 'manifest.json')))
    chars = json.load(open(os.path.join(render_dir, 'chars.json')))

    # big terrain pieces wrongly split off as sprites stay in the backdrop
    def terrain(s):
        f = s['foot']
        return s['id'].split('-')[0] in ('outside', 'grounds', 'street') and f[1] - f[0] > 4 and f[3] - f[2] > 4
    man['sprites'] = [s for s in man['sprites'] if not terrain(s)]

    images = {}
    for s in man['sprites']:
        images[s['name']] = Image.open(os.path.join(render_dir, 's', s['name'] + '.png'))
        if s.get('shadow'):
            images[s['name'] + '.sh'] = Image.open(os.path.join(render_dir, 's', s['name'] + '.sh.png'))
    for name in chars:
        images['c:' + name] = Image.open(os.path.join(render_dir, 'c', name + '.png'))

    placed, pages = shelf_pack([(k, im.width, im.height) for k, im in images.items()])
    sheets = [Image.new('RGBA', (PAGE, PAGE), (0, 0, 0, 0)) for _ in range(pages)]
    table = {}
    for k, im in images.items():
        p, x, y = placed[k]
        sheets[p].paste(im.convert('RGBA'), (x, y))
        table[k] = [p, x, y, im.width, im.height]
    for i, sh in enumerate(sheets):
        # trim the last page to the used height
        bbox = sh.getbbox() or (0, 0, 1, 1)
        sh = sh.crop((0, 0, PAGE, min(PAGE, bbox[3] + PAD)))
        sh.save(os.path.join(out, f'atlas-{i}.webp'), quality=92, method=6)

    backdrop = []
    for c in man['backdrop']['chunks']:
        name = c['img'].replace('.jpg', '.webp')
        Image.open(os.path.join(render_dir, c['img'])).save(os.path.join(out, name), quality=88, method=6)
        backdrop.append({**c, 'img': name})

    presence = {}
    for lvl in LEVELS:
        for pid in glb_parts(os.path.join(glb_dir, f'{hotel}-L{lvl}.glb')):
            presence.setdefault(pid, []).append(lvl)

    pack = {
        'hotel': hotel, 'tileW': man['tileW'], 'ppu': man['ppu'], 'pages': pages,
        'backdrop': backdrop, 'sprites': man['sprites'], 'chars': chars,
        'table': table, 'presence': presence,
    }
    with open(os.path.join(out, 'pack.json'), 'w') as f:
        json.dump(pack, f, separators=(',', ':'))
    lines = [
        '// generated by tools/sprites/pack.py — do not edit',
        'export default {',
        "  pack: require('./pack.json'),",
        '  pages: [' + ', '.join(f"require('./atlas-{i}.webp')" for i in range(pages)) + '],',
        '  backdrop: [' + ', '.join(f"require('./{b['img']}')" for b in backdrop) + '],',
        '};',
        '',
    ]
    with open(os.path.join(out, 'index.js'), 'w') as f:
        f.write('\n'.join(lines))
    write_registry(assets)
    size = sum(os.path.getsize(os.path.join(out, f)) for f in os.listdir(out))
    print(f'{hotel}: {len(images)} images on {pages} pages, {len(backdrop)} backdrop chunks, {size / 1e6:.1f} MB')


if __name__ == '__main__':
    main()
